name: turbo_template
description: "Ultra wide turbo flutter template"

version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  email_validator: ^3.0.0
  url_launcher: ^6.3.1
  json_annotation: ^4.9.0
  veto: ^0.0.15
  loglytics: ^0.15.0
  package_info_plus: ^8.1.3
  url_strategy: ^0.3.0
  firebase_auth: ^5.4.1
  turbo_response: ^0.2.6
  hive_ce: ^2.9.0
  firebase_core: ^3.10.1
  flutter_animate: ^4.5.2
  provider: ^6.1.2
  rxdart: ^0.28.0
  flutter_intl: ^0.0.1
  cloud_firestore: ^5.6.2
  informers: ^0.0.3+1
  go_router: ^14.7.1
  flutter_svg: ^2.0.17
  auto_size_text: ^3.0.0
  connectivity_plus: ^6.1.2
  flutter_secure_storage: ^9.2.4
  haptic_feedback: ^0.5.1+1
  firebase_storage: ^12.4.1
  cloud_functions: ^5.3.2
  soft_edge_blur: ^0.1.3
  turbo_firestore_api: ^0.4.2
  get_it: ^8.0.3
  shadcn_flutter:
    path: ./forks/shadcn_flutter
  flutter_phoenix: ^1.1.1
  cached_network_image: ^3.4.1
  smooth_sheets: ^0.10.2
  device_preview_plus: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  hive_ce_generator: ^1.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/pngs/
    - assets/rive/
    - assets/svgs/
    - assets/audio/
    - assets/jpg/
    - assets/md/

  fonts:
    - family: BootstrapIcons
      fonts:
        - asset: "packages/shadcn_flutter/icons/BootstrapIcons.otf"
    - family: RadixIcons
      fonts:
        - asset: "packages/shadcn_flutter/icons/RadixIcons.otf"
    - family: "GeistSans"
      fonts:
        - asset: "packages/shadcn_flutter/fonts/Geist-Black.otf"
          weight: 800
        - asset: "packages/shadcn_flutter/fonts/Geist-Bold.otf"
          weight: 700
        - asset: "packages/shadcn_flutter/fonts/Geist-Light.otf"
          weight: 300
        - asset: "packages/shadcn_flutter/fonts/Geist-Medium.otf"
          weight: 500
        - asset: "packages/shadcn_flutter/fonts/Geist-SemiBold.otf"
          weight: 600
        - asset: "packages/shadcn_flutter/fonts/Geist-Thin.otf"
          weight: 100
        - asset: "packages/shadcn_flutter/fonts/Geist-UltraBlack.otf"
          weight: 900
        - asset: "packages/shadcn_flutter/fonts/Geist-UltraLight.otf"
          weight: 200
        - asset: "packages/shadcn_flutter/fonts/Geist-Regular.otf"
          weight: 400
    - family: "GeistMono"
      fonts:
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Black.otf"
          weight: 800
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Bold.otf"
          weight: 700
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Light.otf"
          weight: 300
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Medium.otf"
          weight: 500
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Regular.otf"
          weight: 400
        - asset: "packages/shadcn_flutter/fonts/GeistMono-SemiBold.otf"
          weight: 600
        - asset: "packages/shadcn_flutter/fonts/GeistMono-Thin.otf"
          weight: 100
        - asset: "packages/shadcn_flutter/fonts/GeistMono-UltraBlack.otf"
          weight: 900
        - asset: "packages/shadcn_flutter/fonts/GeistMono-UltraLight.otf"
          weight: 200
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          weight: 900

flutter_intl:
  arb_dir: lib/localizations/config
  class_name: Strings
  enabled: true
  main_locale: en
  output_dir: lib/localizations/strings/gen
