// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:turbo_template/turbo/enums/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AuthStepAdapter());
    registerAdapter(DateFormatAdapter());
    registerAdapter(DateTimeAdapter());
    registerAdapter(EmojiAdapter());
    registerAdapter(LocalStorageDtoAdapter());
    registerAdapter(NavigationTabAdapter());
    registerAdapter(SupportedLanguageAdapter());
    registerAdapter(TurboThemeAdapter());
    registerAdapter(TurboThemeModeAdapter());
  }
}
